# Generated by Django 4.0.2 on 2022-02-26 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(choices=[('1-maktab', '1-maktab'), ('2-maktab', '2-maktab'), ('3-maktab', '3-maktab'), ('4-maktab', '4-maktab'), ('5-maktab', '5-maktab'), ('6-maktab', '6-maktab'), ('7-maktab', '7-maktab'), ('8-maktab', '8-maktab'), ('9-maktab', '9-maktab'), ('10-maktab', '10-maktab'), ('11-maktab', '11-maktab'), ('12-maktab', '12-maktab'), ('13-maktab', '13-maktab'), ('14-maktab', '14-maktab'), ('15-maktab', '15-maktab'), ('16-maktab', '16-maktab'), ('17-maktab', '17-maktab'), ('18-maktab', '18-maktab'), ('19-maktab', '19-maktab'), ('20-maktab', '22-maktab'), ('23-maktab', '23-maktab'), ('24-maktab', '24-maktab'), ('25-maktab', '25-maktab'), ('26-maktab', '26-maktab')], default='1-maktab', max_length=20, unique=True, verbose_name='Maktab nomi')),
                ('situated_district', models.CharField(default='Rishton', max_length=30, verbose_name='Maktab joylashgan tuman')),
                ('situated_region', models.CharField(default="Farg'ona", max_length=30, verbose_name='Maktab joylashgan viloyat')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('principal_fname', models.CharField(max_length=20)),
                ('principal_lname', models.CharField(max_length=20)),
                ('principal_phone', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shcool_principal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
