# Generated by Django 4.0.2 on 2022-02-26 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_remove_school_principal_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(help_text='+99801112233', max_length=15, unique=True)),
                ('user_status', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacheruser', to=settings.AUTH_USER_MODEL)),
                ('work_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schooluser', to='attendance.school')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
