# Generated by Django 4.0.2 on 2022-02-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_teacher_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_place',
            field=models.CharField(choices=[('1-maktab', '1-maktab'), ('2-maktab', '2-maktab'), ('3-maktab', '3-maktab'), ('4-maktab', '4-maktab'), ('5-maktab', '5-maktab'), ('6-maktab', '6-maktab'), ('7-maktab', '7-maktab'), ('8-maktab', '8-maktab'), ('9-maktab', '9-maktab'), ('10-maktab', '10-maktab'), ('11-maktab', '11-maktab'), ('12-maktab', '12-maktab'), ('13-maktab', '13-maktab'), ('14-maktab', '14-maktab'), ('15-maktab', '15-maktab'), ('16-maktab', '16-maktab'), ('17-maktab', '17-maktab'), ('18-maktab', '18-maktab'), ('19-maktab', '19-maktab'), ('20-maktab', '22-maktab'), ('23-maktab', '23-maktab'), ('24-maktab', '24-maktab'), ('25-maktab', '25-maktab'), ('26-maktab', '26-maktab')], default='1-maktab', max_length=20, unique=True, verbose_name='Maktab nomi'),
        ),
    ]
