# Generated by Django 4.0.2 on 2022-02-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_teacher_work_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('student_class', models.CharField(choices=[('1-A sinf', '1-A sinf'), ('1-B sinf', '1-B sinf'), ('1-C sinf', '1-C sinf'), ('1-D sinf', '1-D sinf'), ('1-E sinf', '1-E sinf'), ('2-A sinf', '2-A sinf'), ('2-B sinf', '2-B sinf'), ('2-C sinf', '2-C sinf'), ('2-D sinf', '2-D sinf'), ('2-E sinf', '2-E sinf'), ('3-A sinf', '3-A sinf'), ('3-B sinf', '3-B sinf'), ('3-C sinf', '3-C sinf'), ('3-D sinf', '3-D sinf'), ('3-E sinf', '3-E sinf'), ('4-A sinf', '4-A sinf'), ('4-B sinf', '4-B sinf'), ('4-C sinf', '4-C sinf'), ('4-D sinf', '4-D sinf'), ('4-E sinf', '4-E sinf'), ('5-A sinf', '5-A sinf'), ('5-B sinf', '5-B sinf'), ('5-C sinf', '5-C sinf'), ('5-D sinf', '5-D sinf'), ('5-E sinf', '5-E sinf'), ('6-A sinf', '6-A sinf'), ('6-B sinf', '6-B sinf'), ('6-C sinf', '6-C sinf'), ('6-D sinf', '6-D sinf'), ('6-E sinf', '6-E sinf'), ('7-A sinf', '7-A sinf'), ('7-B sinf', '7-B sinf'), ('7-C sinf', '7-C sinf'), ('7-D sinf', '7-D sinf'), ('7-E sinf', '7-E sinf'), ('8-A sinf', '8-A sinf'), ('8-B sinf', '8-B sinf'), ('8-C sinf', '8-C sinf'), ('8-D sinf', '8-D sinf'), ('8-E sinf', '8-E sinf'), ('9-A sinf', '9-A sinf'), ('9-B sinf', '9-B sinf'), ('9-C sinf', '9-C sinf'), ('9-D sinf', '9-D sinf'), ('9-E sinf', '9-E sinf'), ('10-A sinf', '10-A sinf'), ('10-B sinf', '10-B sinf'), ('10-C sinf', '10-C sinf'), ('10-D sinf', '10-D sinf'), ('10-E sinf', '10-E sinf'), ('11-A sinf', '11-A sinf'), ('11-B sinf', '11-B sinf'), ('11-C sinf', '11-C sinf'), ('11-D sinf', '11-D sinf'), ('11-E sinf', '11-E sinf')], max_length=20)),
                ('student_gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10)),
                ('present', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('student_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_student', to='attendance.school')),
                ('student_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student', to='attendance.teacher')),
            ],
        ),
    ]
