# Generated by Django 4.0.2 on 2022-02-27 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0007_alter_school_principal_alter_school_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='principal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shcool_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(choices=[('1-maktab', '1-maktab'), ('2-maktab', '2-maktab'), ('3-maktab', '3-maktab'), ('4-maktab', '4-maktab'), ('5-maktab', '5-maktab'), ('6-maktab', '6-maktab'), ('7-maktab', '7-maktab'), ('8-maktab', '8-maktab'), ('9-maktab', '9-maktab'), ('10-maktab', '10-maktab'), ('11-maktab', '11-maktab'), ('12-maktab', '12-maktab'), ('13-maktab', '13-maktab'), ('14-maktab', '14-maktab'), ('15-maktab', '15-maktab'), ('16-maktab', '16-maktab'), ('17-maktab', '17-maktab'), ('18-maktab', '18-maktab'), ('19-maktab', '19-maktab'), ('20-maktab', '22-maktab'), ('23-maktab', '23-maktab'), ('24-maktab', '24-maktab'), ('25-maktab', '25-maktab'), ('26-maktab', '26-maktab')], default='1-maktab', max_length=20, unique=True, verbose_name='Maktab nomi'),
        ),
    ]
