# Generated by Django 4.0.2 on 2022-02-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_school_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_student', to='attendance.school', verbose_name='Maktabi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student', to='attendance.teacher', verbose_name="O'qituvchi"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(help_text='+99801112233', max_length=15, unique=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_status',
            field=models.CharField(max_length=100, verbose_name='Lavozimi'),
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('1-A sinf', '1-A sinf'), ('1-B sinf', '1-B sinf'), ('1-C sinf', '1-C sinf'), ('1-D sinf', '1-D sinf'), ('1-E sinf', '1-E sinf'), ('2-A sinf', '2-A sinf'), ('2-B sinf', '2-B sinf'), ('2-C sinf', '2-C sinf'), ('2-D sinf', '2-D sinf'), ('2-E sinf', '2-E sinf'), ('3-A sinf', '3-A sinf'), ('3-B sinf', '3-B sinf'), ('3-C sinf', '3-C sinf'), ('3-D sinf', '3-D sinf'), ('3-E sinf', '3-E sinf'), ('4-A sinf', '4-A sinf'), ('4-B sinf', '4-B sinf'), ('4-C sinf', '4-C sinf'), ('4-D sinf', '4-D sinf'), ('4-E sinf', '4-E sinf'), ('5-A sinf', '5-A sinf'), ('5-B sinf', '5-B sinf'), ('5-C sinf', '5-C sinf'), ('5-D sinf', '5-D sinf'), ('5-E sinf', '5-E sinf'), ('6-A sinf', '6-A sinf'), ('6-B sinf', '6-B sinf'), ('6-C sinf', '6-C sinf'), ('6-D sinf', '6-D sinf'), ('6-E sinf', '6-E sinf'), ('7-A sinf', '7-A sinf'), ('7-B sinf', '7-B sinf'), ('7-C sinf', '7-C sinf'), ('7-D sinf', '7-D sinf'), ('7-E sinf', '7-E sinf'), ('8-A sinf', '8-A sinf'), ('8-B sinf', '8-B sinf'), ('8-C sinf', '8-C sinf'), ('8-D sinf', '8-D sinf'), ('8-E sinf', '8-E sinf'), ('9-A sinf', '9-A sinf'), ('9-B sinf', '9-B sinf'), ('9-C sinf', '9-C sinf'), ('9-D sinf', '9-D sinf'), ('9-E sinf', '9-E sinf'), ('10-A sinf', '10-A sinf'), ('10-B sinf', '10-B sinf'), ('10-C sinf', '10-C sinf'), ('10-D sinf', '10-D sinf'), ('10-E sinf', '10-E sinf'), ('11-A sinf', '11-A sinf'), ('11-B sinf', '11-B sinf'), ('11-C sinf', '11-C sinf'), ('11-D sinf', '11-D sinf'), ('11-E sinf', '11-E sinf')], max_length=20, verbose_name='Sinf turi')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('class_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_class', to='attendance.school', verbose_name='Maktabi')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class', to='attendance.teacher', verbose_name="O'qituvchi")),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.schoolclass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_student', to='attendance.schoolclass', verbose_name='Sinfi'),
        ),
    ]
