# Generated by Django 4.0.2 on 2022-03-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendance_school_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='school',
        ),
    ]
