# Generated by Django 4.0.2 on 2022-03-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_remove_attendance_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_school',
        ),
    ]
