# Generated by Django 4.0.2 on 2022-03-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_remove_attendance_class_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.schoolclass'),
            preserve_default=False,
        ),
    ]
