# Generated by Django 4.0.2 on 2022-03-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_attendance_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='classes',
        ),
    ]
