# Generated by Django 4.0.2 on 2022-03-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_remove_attendance_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='school_classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.schoolclass'),
            preserve_default=False,
        ),
    ]
