# Generated by Django 4.0.2 on 2022-03-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_attendance_school_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='school_classes',
            new_name='school_class',
        ),
    ]
