# Generated by Django 4.0.2 on 2022-03-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_rename_school_classes_attendance_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='school_class',
        ),
    ]
