# Generated by Django 4.0.2 on 2022-03-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_remove_attendance_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark_attendance',
            field=models.CharField(choices=[('Bor', 'Bor'), ("Yo'q", "Yo'q"), ('Sababli', 'Sababli')], max_length=50),
        ),
    ]
