# Generated by Django 4.0.2 on 2022-03-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_alter_attendance_mark_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('Yigit', 'Yigit'), ('Qiz', 'Qiz')], max_length=10, verbose_name='Jinsi'),
        ),
    ]
