# Generated by Django 4.0.2 on 2022-03-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_alter_student_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10, verbose_name='Jinsi'),
        ),
    ]
