# Generated by Django 4.0.2 on 2022-03-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_alter_student_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cause',
            field=models.IntegerField(default=0, verbose_name='Sababli'),
        ),
        migrations.AlterField(
            model_name='student',
            name='absent',
            field=models.IntegerField(default=0, verbose_name="Yo'q"),
        ),
        migrations.AlterField(
            model_name='student',
            name='present',
            field=models.IntegerField(default=0, verbose_name='Bor'),
        ),
    ]
