# Generated by Django 4.0.2 on 2022-03-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_alter_csv_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total',
            field=models.FloatField(blank=True, default=0, verbose_name='Umumiy reyting (%)'),
        ),
    ]
