# Generated by Django 4.0.2 on 2022-03-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total',
            field=models.FloatField(blank=True, verbose_name='Umumiy reyting (%)'),
        ),
    ]
