# Generated by Django 4.0.2 on 2022-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_remove_student_total_alter_student_absent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='absent',
            field=models.IntegerField(default=0, verbose_name="Yo'q"),
        ),
        migrations.AlterField(
            model_name='student',
            name='cause',
            field=models.IntegerField(default=0, verbose_name='Sababli'),
        ),
        migrations.AlterField(
            model_name='student',
            name='present',
            field=models.IntegerField(default=0, verbose_name='Bor'),
        ),
    ]
