# Generated by Django 4.0.2 on 2022-03-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_alter_student_absent_alter_student_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total',
            field=models.FloatField(blank=True, default=1, verbose_name='Umumiy reyting (%)'),
            preserve_default=False,
        ),
    ]
